# Generated by Django 3.2 on 2022-08-23 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('cost_per_sqm', models.IntegerField()),
                ('entrances', models.IntegerField()),
                ('floors', models.IntegerField()),
                ('apartments', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, null=True)),
                ('date_purchase', models.DateField(null=True)),
                ('status', models.CharField(choices=[('Sold', 'Выкуп'), ('Partially sold', 'Выкуп не до конца'), ('Separated', 'Расторгнуто'), ('Not sold', 'Не продано')], default='Not sold', max_length=30)),
                ('squire', models.IntegerField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.block')),
            ],
        ),
    ]
