# Generated by Django 3.2 on 2022-08-23 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='apartments',
            new_name='number_apartments',
        ),
    ]
