# Generated by Django 3.2 on 2022-08-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_apartments_block_number_apartments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='date_purchase',
            field=models.DateField(blank=True, null=True),
        ),
    ]
