# Generated by Django 3.2 on 2022-08-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_apartment_date_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='surname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
